name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild . /t:Restore /p:Configuration=${{ matrix.configuration }} /p:Platform=x64
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Build the application
      run: msbuild . /p:Configuration=${{ matrix.configuration }} /p:Platform=x64
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.2
      with:
        filename: release.zip
        path: .
        directory: GoodixTools\bin\${{ matrix.configuration }}
        type: zip

    - uses: actions/upload-artifact@v3
      with:
        name: release.zip
        path: GoodixTools\bin\${{ matrix.configuration }}\release.zip
